### ISSUE TITLE
Generated OpenAPI doesn't contain expected paths in 0.83.1

### ISSUE THREAD

**Issue by kgilpin** [getappmap/appmap-ruby#251]
Reported by @ MGatner

Unfortunately the latest release (0.83.1) appears to be working even less than before. Running the tests works (though with a cryptic warning message):

$ APPMAP=true bundle exec rails test
process_action not found on ActionController::Instrumentation
process_action not found on ActionController::Instrumentation

Run options: --seed 41334
...
But then when I try to generate the docs I now get empty scaffolds. Entire file contents:

```yaml
---
openapi: 3.0.1
info:
  title: Enroll API
  version: v1
paths: {}
components: 
servers:
- url: http://{defaultHost}
  variables:
    defaultHost:
      default: localhost:3000
```

In the previous version this at least had a helpful base that I cold finish filling out myself.

**Comment by MGatner** [comment]
Let me know how I can help.

**Comment by kgilpin** [comment]
Thank you. Can you attach your package.json, yarn.lock, Gemfile,
Gemfile.lock? Then we should be able to reproduce this and fix it.

**Comment by kgilpin** [comment]
@MGatner nudge to see if you can provide the package files ^^ thanks!

**Comment by MGatner** [comment]
This is a Rails API instance so we don't have any JS packages, but here are the Gem files.

[Archive.zip](https://github.com/applandinc/appmap-ruby/files/8670725/Archive.zip)

**Comment by kgilpin** [comment]
Hmm, I don't see the appmap gem in here? What command are you running to generate OpenAPI?

PS we are going to remove those scary-ish but harmless warnings as well.

**Comment by MGatner** [comment]
Oh sorry, this is the project before adding AppMap. I can provide the version with if you like - all I did was Bundle install appmap.

**Comment by MGatner** [comment]
Here are the notes I took on how to integrate it:

***

# Swagger

## Configuration

Using [AppMap](https://appland.com/docs/reference/appmap-ruby.html) to generate Swagger files.
1. Followed the Installation Guide
2. Configured for "Recording Test Case > Minitest"
3. Added "OpenAPI (Swagger) generation" to the config

## Mapping the App

Record test output as maps by setting the environment variable:
```bash
$ APPMAP=true bundle exec rails test
```
> **Note:** This seems to be failing due to some vendor bug. See [appmap-ruby#226](https://github.com/applandinc/appmap-ruby/issues/226)

## Generating Swagger YML

Run the provided Rails task:
```bash
$ bundle exec rake appmap:swagger
```

This will generate the Swagger YML files in the root of the project at **swagger/**.

**Comment by kgilpin** [comment]
Completed.
