### ISSUE TITLE
mach-o file, but is an incompatible architecture (have 'x86_64', need 'arm64e')

### ISSUE THREAD

**Issue by petecheslock** [getappmap/appmap-ruby#286]
These issues manifest as follows:

```
Error: An error occurred while running the command: �[31mbundle exec appmap-agent-init�[39m
The command exited with code �[31m1�[39m
�[31m> �[39mbundler: failed to load command: appmap-agent-init (/Users/user/.asdf/installs/ruby/2.7.6/bin/appmap-agent-init)
�[31m> �[39m/Users/user/.asdf/installs/ruby/2.7.6/lib/ruby/gems/2.7.0/gems/appmap-0.90.1/lib/appmap/agent.rb:11:in 
`require_relative': dlopen(/Users/user/.asdf/installs/ruby/2.7.6/lib/ruby/gems/2.7.0/gems/appmap-
0.90.1/lib/appmap/appmap.bundle, 0x0009): tried: '/Users/user/.asdf/installs/ruby/2.7.6/lib/ruby/gems/2.7.0/gems/appmap-
0.90.1/lib/appmap/appmap.bundle' (mach-o file, but is an incompatible architecture (have 'x86_64', need 'arm64e')), 
'/usr/local/lib/appmap.bundle' (no such file), '/usr/lib/appmap.bundle' (no such file) - 
/Users/user/.asdf/installs/ruby/2.7.6/lib/ruby/gems/2.7.0/gems/appmap-0.90.1/lib/appmap/appmap.bundle (LoadError)
```

We should detect the string `mach-o file, but is an incompatible architecture (have 'x86_64', need 'arm64e')` as well as a non-zero exit code. If both occur, we put a suggestion in the console output for the user to quickly learn how to fix it. Preferably this would be a link to an FAQ entry on our site which would explain that in this case the solution is to run:

`gem uninstall appmap; bundle`

Background: Basically, we need to make sure appmap gem is already installed when npx tries to install it. This happens when you have native ruby but emulated node. Running node sets up the Rosetta environment which causes gem to use x64 compiler to build the gem even though ruby is native (because node executes gem in its rosetta'd, environment).

**Comment by dividedmind** [comment]
BTW, I just discovered https://www.unix.com/man-page/osx/1/arch/ — it seems that maybe it'd work to run `arch --arch arm64e bundle`.
