### ISSUE TITLE
Don't display warning that says "AppMap recording is enabled" -- appmap-ruby

### ISSUE THREAD

**Issue by symwell** [getappmap/appmap-ruby#291]
In `appmap-python`, when Appmap is enabled users see a warning when their testcases run that says
```
[2022-10-19 19:33:01,306] WARNING appmap._implementation.detect_enabled: AppMap recording is enabled because APPMAP=true
WARNING:appmap._implementation.detect_enabled:AppMap recording is enabled because APPMAP=true
```

Let's downgrade the logging level to something that isn't visible.  Users should not get console noise for setting up APPMAP=true.

Do this in `appmap-ruby`. There's a similar issue for `appmap-python` https://github.com/getappmap/appmap-python/issues/182

**Comment by symwell** [comment]
Given that most `appmap-ruby` users seem to install successfully, and that I added this task as a paraller to `appmap-python` where they weren't, I'm moving this back to Under Consideration.

**Comment by kgilpin** [comment]
IMO it's important to give users feedback that AppMap is enabled and working.
