### ISSUE TITLE
Auto generated OpenApi schema doesn't include $ref with nested object 

### ISSUE THREAD

**Issue by nhien-cerebral** [getappmap/appmap-ruby#297]
Currently I identified an issue with auto generated open api schema. There is no $ref with nested object, and the generator only goes down one level in the schema.
For example I created an API with rendered json like this
`render json: {
      page: {
        page_index: 1,
        page_size: 1,
        page_offset: 0
        page_prev_offset: 0      
       }
    }`
The generated open api contains only the page with object type with out any $ref to link to the open api definition.
<img width="269" alt="image" src="https://user-images.githubusercontent.com/99308250/202520859-6f0c8e11-ddcf-4a7f-80fa-7a5819ca1cc6.png">
Do we have any solutions for that?  thank you everyone who contributed to this awesome library.

**Comment by kgilpin** [comment]
Thanks @nhien-cerebral we will discuss this internally and see what we can propose as a solution.

**Comment by kgilpin** [comment]
@nhien-cerebral the solution will require two parts:

1) appmap-ruby needs to dig deeper into the response object to output the nested properties
2) the openapi generator needs to report this additional detail

@dividedmind has offered to look into this.

**Comment by dividedmind** [comment]
> @dividedmind has offered to look into this.

Did I now? That's news to me ;) But I certainly can and will. I'll keep you posted, @nhien-cerebral !

**Comment by nhien-cerebral** [comment]
Perfect, thank you so much guys for being really active on that. I appreciate all of you guys

**Comment by kgilpin** [comment]
The first thing we need to do is support nested properties in the OpenAPI schema - so here's a PR for that - https://github.com/getappmap/appmap-js/pull/864

**Comment by nhien-cerebral** [comment]
> The first thing we need to do is support nested properties in the OpenAPI schema - so here's a PR for that - [getappmap/appmap-js#864](https://github.com/getappmap/appmap-js/pull/864)

May I have a silly question, I forgot to mention about the nested object inside an array.
If we have the object for example 
`render json: { pages: [{ page_index: 1, page_size: 1, page_offset: 0 page_prev_offset: 0 } , { page_index: 2, page_size: 3, page_offset: 0 page_prev_offset: 0 } ]`
Now the open api generation returned the "array" only, does this PR cover this scenario?
Sorry for having so many questions here

**Comment by kgilpin** [comment]
I’ll check that it describes the array type

**Comment by kgilpin** [comment]
There is a new release of appmap-ruby - 0.94.0 - https://github.com/getappmap/appmap-ruby/compare/v0.93.5...v0.94.0

It would be helpful if you can make an AppMap of your code using this new version. You don't have to make all the tests, just the one(s) that are relevant to this issue. Then if you can look in the AppMap for `properties` [as described here](https://github.com/getappmap/appmap-ruby/compare/v0.93.5...v0.94.0). If you can respond to this issue with some of the `properties` from your code, we can confirm that this is the right data for the OpenAPI generation.

**Comment by nhien-cerebral** [comment]
@kgilpin  Hi I've completed a quick check with the new version but it seems schema parsing missing some properties, could you please verify with more properties?
`let(:max_depth) { nil }
    let(:schema) {
    options = {}
    options[:max_depth] = max_depth if max_depth
    AppMap::ValueInspector.detect_schema value, **options
    }
    let(:value)   { JSON.parse(response.body) }`
    
    And then, I compared the values with response.body with schema by this way
    `puts JSON.parse(response.body)
      puts schema.to_json`
    the output of puts JSON.parse(response.body)
`{"plans"=>[{"id"=>1, 
    "category"=>"abc", 
    "chargebee_plan_id"=>"abc", 
    "country"=>"vn", 
    "created_at"=>"2022-11-23T06:03:09.399Z", 
    "is_current"=>true, 
    "is_insurance"=>false, 
    "is_public"=>true, 
    "offering_key"=>"abc", 
    "plan_type"=>nil, 
    "price"=>1, 
    "stripe_plan_id"=>nil, 
    "stripe_price_id"=>nil,
    "updated_at"=>"2022-11-23T06:03:09.399Z"}], 
    "default_plan_id"=>1, 
    "page"=>{"page_index"=>1, 
    "page_size"=>20, 
    "page_offset"=>1, 
    "page_prev_offset"=>1}}
}`

    the output of `puts schema.to_json
    `{
    "properties": [
        {
            "name": "plans",
            "class": "Array",
            "properties": [
                {
                    "name": "id",
                    "class": "Integer"
                },
                {
                    "name": "category",
                    "class": "String"
                },
                {
                    "name": "chargebee_plan_id",
                    "class": "String"
                },
                {
                    "name": "country",
                    "class": "NilClass"
                },
                {
                    "name": "created_at",
                    "class": "String"
                },
                {
                    "name": "is_current",
                    "class": "TrueClass"
                },
                {
                    "name": "is_insurance",
                    "class": "FalseClass"
                },
                {
                    "name": "offering_key",
                    "class": "String"
                },
                {
                    "name": "price",
                    "class": "Float"
                }
            ]
        },
        {
            "name": "page",
            "class": "Hash",
            "properties": [
                {
                    "name": "page_size",
                    "class": "Integer"
                }
            ]
        }
    ]
}`

**Comment by kgilpin** [comment]
@nhien-cerebral I've pushed a new branch with a fix for this - https://github.com/getappmap/appmap-ruby/compare/fix/nested-properties?expand=1#diff-984e2437fc02912cbf493797508b5f1cbe7596099f71ff0ddc5e906a189471ccR72

Take a look and let me know what you think. If you want to try this branch, you can build it using `bundle exec rake compile`.

**Comment by kgilpin** [comment]
Fixed via #299 and https://github.com/getappmap/appmap-js/pull/864 ; closing.

**Comment by nhien-cerebral** [comment]
I checked and it works smoothly now
Thank guys for supporting, looking forward to see how openapi generation leverages this implementation :)
