### ISSUE TITLE
AppMap documentation improvements

### ISSUE THREAD

**Issue by cholguin86** [getappmap/appmap-ruby#318]
I am creating this issue to improve the AppMap documentation based on my experience with AppMap using the ruby gem. I want to share some important facts that should be better documented. Current documentation is available here: https://appmap.io/docs/reference/appmap-ruby.html

When AppMap is enabled and the specs are run, The following actions will always be executed:

- **AppMaps will be created:** There is not any setting to skip this process, AppMaps are always generated. Initially, we thought that we could control this with the _packages_ setting (_appmap.yml_ file), however, the purpose of this setting is different (it determines the AppMaps content ).  Sometimes it is useful to generate the AppMaps for a specific list of specs without a dedicated execution, for example, we have a pipeline to run 10 specs, however, only 2 require recording. We don't want to run twice this pipeline: one execution for QA purposes and the second execution for the specs that we want to record.
- **HTTP requests are recorded:** We should indicate this is the default behavior. 
- **SQL queries are recorded:**: There is not any way to disable this recording. 

Please keep in mind those documentation improvements. I think this will help developers avoid confusion. Thanks!

**Comment by kgilpin** [comment]
Hi @cholguin86 thanks for your submission. 

If you are running rspec tests, you can disable AppMaps for a test or example group using the tag `appmap: false`

You can also disable AppMaps completely using the env var `APPMAP=false`

HTTP request and SQL, along with other specifically labeled code, is always recorded if AppMaps are enabled. We will use update the docs to make this more prominent.

**Comment by kgilpin** [comment]
Fixed by https://github.com/getappmap/applandinc.github.io/pull/983
