### ISSUE TITLE
rails 7 failing loading assets with error ActionController::RoutingError (No route matches [GET]

### ISSUE THREAD

**Issue by spaquet** [getappmap/appmap-ruby#329]
Environment:
Rails 7.0.4.3
Ruby 3.2.2
Using Esbuild and Tailwind CSS
AppMap 0.99.3 (0.99.1 not affected. 0.99.2 didn't test)

After upgrading to AppMap 0.99.3 the app is unable to access the application.js and application.css in the assets folder even when the app is configured to serve static content.

ActionController::RoutingError (No route matches [GET] /assets/application-xxxxx.css
ActionController::RoutingError (No route matches [GET] /assets/application-yyyyy.js

Current workaround is to rollback to version 0.99.1

**Comment by spaquet** [comment]
I forgot to mention that this is a blocker... since the .js and .css files are not loaded by the client and thus the app does not work ;-)

**Comment by kgilpin** [comment]
@spaquet thank you for reporting this. I'm sorry that you encountered this problem, we'll be working on a fix. Please watch this issue so that we can provide you with a pre-release to test in your environment and help us confirm that the issue is resolved.

In the meantime, we've yanked 0.99.3 from Rubygems.

**Comment by dividedmind** [comment]
Thanks @spaquet for the report, I can confirm reproduction of this issue, working on a fix. I'll keep you posted!

**Comment by dividedmind** [comment]
Hi @spaquet , would you mind checking if #330 fixes your problem? You should be able to use it by using

    gem 'appmap', github: 'getappmap/appmap-ruby', branch: 'fix/serving-static-assets'

in your `Gemfile`. Thanks!

**Comment by spaquet** [comment]
@dividedmind I'm testing it.

**Comment by spaquet** [comment]
Looks like it's working as expected. You may want to have other user's feedbacks.
I had to force the reinstall from git, but besides of that it looks good to me.
