### ISSUE TITLE
appmap_dir config param in appmap.yml does not work

### ISSUE THREAD

**Issue by sgrigson** [getappmap/appmap-ruby#345]
You cannot override the output directory because it's harcoded.

https://github.com/getappmap/appmap-ruby/blob/d99db94328781b92cb9590bc8bce84f9f262863f/lib/appmap/middleware/remote_recording.rb#L106

We *should* be able to set `appmap_dir` to something other than `tmp/appmap` but at this point in time it does not seem to be referencing the parameter during recording.

**Comment by kgilpin** [comment]
Hi, the `appmap_dir` is currently designed to be advisory to other tools about where the AppMaps will be located, rather than a directive to the appmap gem. For example, by consulting the `appmap_dir` the code editor extension can watch only one specific directory for AppMaps, rather than having to watch the whole project.

Where do you want the AppMaps to go, and what is the purpose? Sharing that information will help us to assess the best course of action.

**Comment by sgrigson** [comment]
I guess it sort of defeats the point to have an 'advisory' about where the files will be written when they'll only be written one place.

I'm attempting to create OpenApi files by running an AppMap for Mastodon.

The problem is that Mastodon already uses the tmp folder and periodically will *clear* the folder, often while in the middle of generating an appmap.

So I need to write it to a non 'tmp' folder location.

**Comment by kgilpin** [comment]
> I guess it sort of defeats the point to have an 'advisory' about where the files will be written when they'll only be written one place.

This is true for Ruby but the other tools support Java, Python, and Node.js as well. They all provide _appmap_dir_ in appmap.yml.

Other tunable settings in the Ruby agent (use environment variables](https://appmap.io/docs/reference/appmap-ruby.html#advanced-runtime-options). So I'd suggest this is the best path forward to make the appmap dir configurable.

**Comment by sgrigson** [comment]
> This is true for Ruby but the other tools support Java, Python, and Node.js as well. They all provide appmap_dir in appmap.yml.

Exactly, take Java for instance. It pretty clearly states that `appmap_dir` is the directory that will be used when recording.

<img width="902" alt="Screenshot 2023-10-31 at 12 37 37 PM" src="https://github.com/getappmap/appmap-ruby/assets/4718523/cab865e1-ba65-484f-be32-dfa0b38b74a3">

And even in the [AppMap Ruby documentation](https://appmap.io/docs/reference/appmap-ruby.html#configuration) under Configuration it says this first:

> When you run your program, the appmap gem reads configuration settings from *appmap.yml* ....

^That suggests pretty strongly that appmap is receiving configuration from appmap.yml, and if it did use that directory during recording, it would match the Java behavior.

> Other tunable settings in the Ruby agent use environment variables...

That would be fine, too, there just isn't an ENV for that for Ruby to set any alternate output directory.
