### ISSUE TITLE
When running a test suite, only first test gets converted to AppMap

### ISSUE THREAD

**Issue by gonzric1** [getappmap/appmap-ruby#356]
Expected Behavior: When I run all tests in a file with many tests, all tests return an appmap accessible via the VSCode/Intellij interface. 

Actual Behavior: Only first test in file generates an appmap. 

When running tests on a file with many tests, all of the files get recorded as a `#{test_name}.appmap.json` file, but only the first test in each file gets converted to a folder and shows up in the appmap extension. 

This seems to happen consistently with controller specs, but not with model specs. 

You can get around this by running each test case individually. However, if I try running all tests in a folder, only the first `it...` statement in each file creates an appmap.

**Comment by kgilpin** [comment]
Hi, can you provide your Ruby version and RSpec version? Maybe rspec has changed in a way that’s outside of our test matrix.

**Comment by gonzric1** [comment]
ruby '3.2.2'
Ruby: ruby 3.2.2

**Comment by kgilpin** [comment]
Related: https://github.com/getappmap/appmap-js/pull/1704

should allow the AppMaps to load regardless of stray “returns”. 

It seems that something in the test environment of this project is maybe a long running thread that’s producing random call events.
