### ISSUE TITLE
Disable request recording is not working in Rails 7.0

### ISSUE THREAD

**Issue by minhdinh-vn** [getappmap/appmap-ruby#362]
I have an issue with Rspec test using Capybara with Ruby 2.7 and Rails 7.0. 
`context 'login with incorrect credentials' do
    before do
      visit new_associate_session_path
      fill_in 'email', with: 'sample@example.com'
      fill_in 'password', with: 'password'
      click_on 'Log in'
    end
    it do
      expect(page).to have_content 'Invalid Email or password.'
    end
  end`
This is the config in `rails_helper`: 
`config.before do |spec|
    unless spec.metadata[:appmap] == true
      spec.metadata[:appmap] = false
    end
  end`
This is the log: 
<img width="937" alt="Screenshot 2024-05-22 at 16 00 18" src="https://github.com/getappmap/appmap-ruby/assets/69226405/fcfaff2d-050d-46b2-95f8-8befba19812f">

If I switch to Rails 6.1, the Rspec test passed.

**Comment by apotterri** [comment]
@minhdinh-vn Thanks very much for reporting this.

Can you upgrade to v1.0.1 and confirm that this problem still occurs? Thanks!

**Comment by minhdinh-vn** [comment]
@apotterri - the issue still happens with version 1.0.1 
<img width="948" alt="image" src="https://github.com/getappmap/appmap-ruby/assets/69226405/ee63ce6a-3d8b-4016-b912-07f95b91a46c">

**Comment by apotterri** [comment]
Thanks very much. We'll take a look.

**Comment by minhdinh-vn** [comment]
@apotterri - adding `require 'appmap/rspec'` to `spec_helper.rb` as documented [here](https://appmap.io/docs/reference/appmap-ruby.html#tests-recording) works with Rails 7. 

Closed this issue.
